### ISSUE TITLE
Multiple individual radiators being added as single accessory

### ISSUE THREAD

**Issue by Lngramos** [duggan/homebridge-technotherm#28]
Hey @duggan,

Big thanks for creating this plugin! It's awesome to finally integrate my radiators with Homebridge - the original app's UX is a nightmare, and you're a lifesaver for making this easier.

So, here's the scoop: I just set up your plugin, hoping to get all my radiators synced up for a smoother control experience. But I hit a snag – Homebridge is recognizing my DSM hub/controller (aka. Smart Box) as the radiator, not the actual heaters. It's like it's lumping everything into one, and I can't control them individually.

Is this something you've seen on your end? I'm not sure if it's a one-off thing with my setup or if the plugin treats different models differently. Ideally, I'd love to have each radiator show up on its own in Homebridge, letting me tweak each one separately.

Any thoughts or fixes on this? I would be happy to dive deeper on this, but wanted to check what you see first just in case you're already aware of this.

**Comment by duggan** [comment]
Hey @Lngramos, I hope you can get it working for you!

I had my own set of these radiators installed a couple of months ago, and was told a couple of weeks before install that I'd be getting a more recent set that didn't require the smartbox, so that might be where the discrepancy is coming in.

If you enable debug mode you may be able to get enough information out of the logs to match up where my code is making assumptions about the API structure that aren't true for your own setup.

Just from what I remember of poking around with the API results, it may be that your [results returned from getGroupedDevices](https://github.com/duggan/homebridge-technotherm/blob/36a89df773b7205a892dee2c8ed967748b12e53a/src/platform.ts#L61) are slightly different from mine.

If it helps, this is an example of the data I receive for groupedDevices:

```json
[
  {
    "id": "f796dce0bc57XXXXXXXXXXXX",
    "name": "Home",
    "devs": [
      {
        "dev_id": "38a7f960XXXXXXX",
        "name": "Living Room",
        "product_id": "0433",
        "fw_version": "1.2.3",
        "serial_id": "2"
      },
      {
        "dev_id": "ef65b760XXXXXXXX",
        "name": "Ash’s Office",
        "product_id": "0433",
        "fw_version": "1.2.3",
        "serial_id": "2"
      },
      {
        "dev_id": "e882fc60XXXXXXXXX",
        "name": "Ross’s Office",
        "product_id": "0433",
        "fw_version": "1.2.3",
        "serial_id": "2"
      }
    ],
    "owner": true
  }
]
```

If you want to take a look at your own API results with more control rather than divining from the logs, this is how I use the client interactively:

Get an interactive Typescript prompt:

```shell
$ npx ts-node
```

Set up the client:

```typescript
import { HelkiClient } from './src/helki_client';
const helki = new HelkiClient('api-lhz', '54bccbfb41a9a5113f0488d0', 'vdivdi', 'USERNAME', 'PASSWORD'); 
```

You should then be able to interact with the available methods to see what they return, and where it might be failing for you, e.g.:

```typescript
const devices = await helki.getGroupedDevices();
JSON.stringify(devices);
```

**Comment by Lngramos** [comment]
Thanks for lightning fast response, @duggan! 😃

The API response I'm getting only shows the Smartbox device, not the individual heaters. Our setups are certainly different, as you predicted.

Here's the snippet from my API response for reference:

```json
[
    {
        "id": "cafeXXXXX",
        "name": "Home",
        "devs": [
            {
                "dev_id": "e698XXXXX",
                "name": "Smartbox",
                "product_id": "0106",
                "fw_version": "1.33.3",
                "serial_id": "12"
            }
        ],
        "owner": true
    }
]
```

The `/api/v2/grouped_devs` API isn't listing the heaters that are peered to my smartbox hub. I'll poke around their app a bit to understand how the "sub-devices" can be individually identified and controlled. I'm guessing that the `product_id` might be key to how the client behaves to different device types.

Thanks for putting me in the right direction! I'll come back with what I find and hopefully land a PR to add support for the [DSM hubs](https://www.technotherm.com/productdetail-accessoiries/dsm-schnittstelle.html) (a.k.a. smartboxes)

**Comment by Lngramos** [comment]
I've raised a PR to fix the discovery for me whilst keeping it compatible with your setup.

Changing the target temperature of the heaters isn't currently working for me due to some API errors. I'll continue to look into this other issue and raise a second PR to cover this separately.
